-- Schema: SCHOOL
CREATE SCHEMA SCHOOL;

-- Table: SCHOOL.COURSES
CREATE TABLE SCHOOL.COURSES (
  COURSEID INTEGER NOT NULL,
  COURSENAME VARCHAR(100) NOT NULL,
  TEACHERID INTEGER NOT NULL,
  PRIMARY KEY (COURSEID),
  UNIQUE (COURSEID));

-- Foreign Key Constraint: SQL230519113755480
ALTER TABLE SCHOOL.COURSES ADD CONSTRAINT SQL230519113755480 FOREIGN KEY (TEACHERID) REFERENCES SCHOOL.TEACHERS (TEACHERID);

-- Table: SCHOOL.ENROLLMENTS
CREATE TABLE SCHOOL.ENROLLMENTS (
  ENROLLMENTID INTEGER NOT NULL,
  STUDENTID INTEGER NOT NULL,
  COURSEID INTEGER NOT NULL,
  PRIMARY KEY (ENROLLMENTID),
  UNIQUE (ENROLLMENTID));

-- Foreign Key Constraint: SQL230519113755510
ALTER TABLE SCHOOL.ENROLLMENTS ADD CONSTRAINT SQL230519113755510 FOREIGN KEY (COURSEID) REFERENCES SCHOOL.COURSES (COURSEID);

-- Foreign Key Constraint: SQL230519113755500
ALTER TABLE SCHOOL.ENROLLMENTS ADD CONSTRAINT SQL230519113755500 FOREIGN KEY (STUDENTID) REFERENCES SCHOOL.STUDENTS (STUDENTID);

-- Table: SCHOOL.STUDENTS
CREATE TABLE SCHOOL.STUDENTS (
  STUDENTID INTEGER NOT NULL,
  STUDENTNAME VARCHAR(100) NOT NULL,
  DATEOFBIRTH DATE NOT NULL,
  PRIMARY KEY (STUDENTID),
  UNIQUE (STUDENTID));

-- Table: SCHOOL.TEACHERS
CREATE TABLE SCHOOL.TEACHERS (
  TEACHERID INTEGER NOT NULL,
  TEACHERNAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (TEACHERID),
  UNIQUE (TEACHERID));

-- View: SCHOOL.STUDENTCOURSESUMMARY
-- Skapa vyer
CREATE VIEW School.StudentCourseSummary AS
SELECT S.StudentName, COUNT(E.CourseID) AS NumberOfCourses
FROM School.Students S
JOIN School.Enrollments E ON S.StudentID = E.StudentID
GROUP BY S.StudentName;

-- View: SCHOOL.TEACHERCOURSESUMMARY
CREATE VIEW School.TeacherCourseSummary AS
SELECT T.TeacherName, COUNT(C.CourseID) AS NumberOfCourses
FROM School.Teachers T
JOIN School.Courses C ON T.TeacherID = C.TeacherID
GROUP BY T.TeacherName;

