-- Skapa Students tabell
CREATE TABLE School.Students (
     StudentID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     StudentName VARCHAR(100) NOT NULL,
     DateOfBirth DATE NOT NULL,
     PRIMARY KEY(StudentID)
);

-- Skapa Teachers tabell
CREATE TABLE School.Teachers (
     TeacherID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     TeacherName VARCHAR(100) NOT NULL,
     PRIMARY KEY(TeacherID)
);

-- Skapa Courses tabell
CREATE TABLE School.Courses (
    CourseID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CourseName VARCHAR(100) NOT NULL,
    TeacherID INT NOT NULL,
    PRIMARY KEY(CourseID),
    FOREIGN KEY(TeacherID) REFERENCES School.Teachers(TeacherID)
);

-- Skapa Enrollments tabell
CREATE TABLE School.Enrollments (
    EnrollmentID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    StudentID INT NOT NULL,
    CourseID INT NOT NULL,
    PRIMARY KEY(EnrollmentID),
    FOREIGN KEY(StudentID) REFERENCES School.Students(StudentID),
    FOREIGN KEY(CourseID) REFERENCES School.Courses(CourseID)
);

-- Skapa vyer
CREATE VIEW School.StudentCourseSummary AS
SELECT S.StudentName, COUNT(E.CourseID) AS NumberOfCourses
FROM School.Students S
         JOIN School.Enrollments E ON S.StudentID = E.StudentID
GROUP BY S.StudentName;

CREATE VIEW School.TeacherCourseSummary AS
SELECT T.TeacherName, COUNT(C.CourseID) AS NumberOfCourses
FROM School.Teachers T
         JOIN School.Courses C ON T.TeacherID = C.TeacherID
GROUP BY T.TeacherName;
