-- Skapa sekvenser

-- Skapa Students tabell
CREATE TABLE Students (
      StudentID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
      StudentName VARCHAR2(100) NOT NULL,
      DateOfBirth DATE NOT NULL
);

-- Skapa Teachers tabell
CREATE TABLE Teachers (
      TeacherID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
      TeacherName VARCHAR2(100) NOT NULL
);

-- Skapa Courses tabell
CREATE TABLE Courses (
     CourseID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
     CourseName VARCHAR2(100) NOT NULL,
     TeacherID INT NOT NULL,
     FOREIGN KEY(TeacherID) REFERENCES Teachers(TeacherID)
);

-- Skapa Enrollments tabell
CREATE TABLE Enrollments (
     EnrollmentID NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
     StudentID INT NOT NULL,
     CourseID INT NOT NULL,
     FOREIGN KEY(StudentID) REFERENCES Students(StudentID),
     FOREIGN KEY(CourseID) REFERENCES Courses(CourseID)
);

-- Skapa vyer
CREATE VIEW StudentCourseSummary AS
SELECT S.StudentName, COUNT(E.CourseID) AS NumberOfCourses
FROM Students S
         JOIN Enrollments E ON S.StudentID = E.StudentID
GROUP BY S.StudentName;

CREATE VIEW TeacherCourseSummary AS
SELECT T.TeacherName, COUNT(C.CourseID) AS NumberOfCourses
FROM Teachers T
         JOIN Courses C ON T.TeacherID = C.TeacherID
GROUP BY T.TeacherName;

-- Skapa Tabell med 50 attribut
CREATE TABLE School.Table50Attributes (
      ID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      Attribute1 VARCHAR2(100) NOT NULL,
      Attribute2 VARCHAR2(100) NOT NULL,
      Attribute3 VARCHAR2(100) NOT NULL,
      Attribute4 VARCHAR2(100) NOT NULL,
      Attribute5 VARCHAR2(100) NOT NULL,
      Attribute6 VARCHAR2(100) NOT NULL,
      Attribute7 VARCHAR2(100) NOT NULL,
      Attribute8 VARCHAR2(100) NOT NULL,
      Attribute9 VARCHAR2(100) NOT NULL,
      Attribute10 VARCHAR2(100) NOT NULL,
      Attribute11 VARCHAR2(100) NOT NULL,
      Attribute12 VARCHAR2(100) NOT NULL,
      Attribute13 VARCHAR2(100) NOT NULL,
      Attribute14 VARCHAR2(100) NOT NULL,
      Attribute15 VARCHAR2(100) NOT NULL,
      Attribute16 VARCHAR2(100) NOT NULL,
      Attribute17 VARCHAR2(100) NOT NULL,
      Attribute18 VARCHAR2(100) NOT NULL,
      Attribute19 VARCHAR2(100) NOT NULL,
      Attribute20 VARCHAR2(100) NOT NULL,
      Attribute21 VARCHAR2(100) NOT NULL,
      Attribute22 VARCHAR2(100) NOT NULL,
      Attribute23 VARCHAR2(100) NOT NULL,
      Attribute24 VARCHAR2(100) NOT NULL,
      Attribute25 VARCHAR2(100) NOT NULL,
      Attribute26 VARCHAR2(100) NOT NULL,
      Attribute27 VARCHAR2(100) NOT NULL,
      Attribute28 VARCHAR2(100) NOT NULL,
      Attribute29 VARCHAR2(100) NOT NULL,
      Attribute30 VARCHAR2(100) NOT NULL,
      Attribute31 VARCHAR2(100) NOT NULL,
      Attribute32 VARCHAR2(100) NOT NULL,
      Attribute33 VARCHAR2(100) NOT NULL,
      Attribute34 VARCHAR2(100) NOT NULL,
      Attribute35 VARCHAR2(100) NOT NULL,
      Attribute36 VARCHAR2(100) NOT NULL,
      Attribute37 VARCHAR2(100) NOT NULL,
      Attribute38 VARCHAR2(100) NOT NULL,
      Attribute39 VARCHAR2(100) NOT NULL,
      Attribute40 VARCHAR2(100) NOT NULL,
      Attribute41 VARCHAR2(100) NOT NULL,
      Attribute42 VARCHAR2(100) NOT NULL,
      Attribute43 VARCHAR2(100) NOT NULL,
      Attribute44 VARCHAR2(100) NOT NULL,
      Attribute45 VARCHAR2(100) NOT NULL,
      Attribute46 VARCHAR2(100) NOT NULL,
      Attribute47 VARCHAR2(100) NOT NULL,
      Attribute48 VARCHAR2(100) NOT NULL,
      Attribute49 VARCHAR2(100) NOT NULL,
      Attribute50 VARCHAR2(100) NOT NULL,
      PRIMARY KEY(ID)
);
-- Skapa Tabell med 25 attribut
CREATE TABLE School.Table25Attributes (
       ID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       Attribute1 VARCHAR2(100) NOT NULL,
       Attribute2 VARCHAR2(100) NOT NULL,
       Attribute3 VARCHAR2(100) NOT NULL,
       Attribute4 VARCHAR2(100) NOT NULL,
       Attribute5 VARCHAR2(100) NOT NULL,
       Attribute6 VARCHAR2(100) NOT NULL,
       Attribute7 VARCHAR2(100) NOT NULL,
       Attribute8 VARCHAR2(100) NOT NULL,
       Attribute9 VARCHAR2(100) NOT NULL,
       Attribute10 VARCHAR2(100) NOT NULL,
       Attribute11 VARCHAR2(100) NOT NULL,
       Attribute12 VARCHAR2(100) NOT NULL,
       Attribute13 VARCHAR2(100) NOT NULL,
       Attribute14 VARCHAR2(100) NOT NULL,
       Attribute15 VARCHAR2(100) NOT NULL,
       Attribute16 VARCHAR2(100) NOT NULL,
       Attribute17 VARCHAR2(100) NOT NULL,
       Attribute18 VARCHAR2(100) NOT NULL,
       Attribute19 VARCHAR2(100) NOT NULL,
       Attribute20 VARCHAR2(100) NOT NULL,
       Attribute21 VARCHAR2(100) NOT NULL,
       Attribute22 VARCHAR2(100) NOT NULL,
       Attribute23 VARCHAR2(100) NOT NULL,
       Attribute24 VARCHAR2(100) NOT NULL,
       Attribute25 VARCHAR2(100) NOT NULL,
       PRIMARY KEY(ID)
);
-- Skapa Tabell med 100 attribut
CREATE TABLE School.Table100Attributes (
       ID INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       Attribute1 VARCHAR2(100) NOT NULL,
       Attribute2 VARCHAR2(100) NOT NULL,
       Attribute3 VARCHAR2(100) NOT NULL,
       Attribute4 VARCHAR2(100) NOT NULL,
       Attribute5 VARCHAR2(100) NOT NULL,
       Attribute6 VARCHAR2(100) NOT NULL,
       Attribute7 VARCHAR2(100) NOT NULL,
       Attribute8 VARCHAR2(100) NOT NULL,
       Attribute9 VARCHAR2(100) NOT NULL,
       Attribute10 VARCHAR2(100) NOT NULL,
       Attribute11 VARCHAR2(100) NOT NULL,
       Attribute12 VARCHAR2(100) NOT NULL,
       Attribute13 VARCHAR2(100) NOT NULL,
       Attribute14 VARCHAR2(100) NOT NULL,
       Attribute15 VARCHAR2(100) NOT NULL,
       Attribute16 VARCHAR2(100) NOT NULL,
       Attribute17 VARCHAR2(100) NOT NULL,
       Attribute18 VARCHAR2(100) NOT NULL,
       Attribute19 VARCHAR2(100) NOT NULL,
       Attribute20 VARCHAR2(100) NOT NULL,
       Attribute21 VARCHAR2(100) NOT NULL,
       Attribute22 VARCHAR2(100) NOT NULL,
       Attribute23 VARCHAR2(100) NOT NULL,
       Attribute24 VARCHAR2(100) NOT NULL,
       Attribute25 VARCHAR2(100) NOT NULL,
       Attribute26 VARCHAR2(100) NOT NULL,
       Attribute27 VARCHAR2(100) NOT NULL,
       Attribute28 VARCHAR2(100) NOT NULL,
       Attribute29 VARCHAR2(100) NOT NULL,
       Attribute30 VARCHAR2(100) NOT NULL,
       Attribute31 VARCHAR2(100) NOT NULL,
       Attribute32 VARCHAR2(100) NOT NULL,
       Attribute33 VARCHAR2(100) NOT NULL,
       Attribute34 VARCHAR2(100) NOT NULL,
       Attribute35 VARCHAR2(100) NOT NULL,
       Attribute36 VARCHAR2(100) NOT NULL,
       Attribute37 VARCHAR2(100) NOT NULL,
       Attribute38 VARCHAR2(100) NOT NULL,
       Attribute39 VARCHAR2(100) NOT NULL,
       Attribute40 VARCHAR2(100) NOT NULL,
       Attribute41 VARCHAR2(100) NOT NULL,
       Attribute42 VARCHAR2(100) NOT NULL,
       Attribute43 VARCHAR2(100) NOT NULL,
       Attribute44 VARCHAR2(100) NOT NULL,
       Attribute45 VARCHAR2(100) NOT NULL,
       Attribute46 VARCHAR2(100) NOT NULL,
       Attribute47 VARCHAR2(100) NOT NULL,
       Attribute48 VARCHAR2(100) NOT NULL,
       Attribute49 VARCHAR2(100) NOT NULL,
       Attribute50 VARCHAR2(100) NOT NULL,
       Attribute51 VARCHAR2(100) NOT NULL,
       Attribute52 VARCHAR2(100) NOT NULL,
       Attribute53 VARCHAR2(100) NOT NULL,
       Attribute54 VARCHAR2(100) NOT NULL,
       Attribute55 VARCHAR2(100) NOT NULL,
       Attribute56 VARCHAR2(100) NOT NULL,
       Attribute57 VARCHAR2(100) NOT NULL,
       Attribute58 VARCHAR2(100) NOT NULL,
       Attribute59 VARCHAR2(100) NOT NULL,
       Attribute60 VARCHAR2(100) NOT NULL,
       Attribute61 VARCHAR2(100) NOT NULL,
       Attribute62 VARCHAR2(100) NOT NULL,
       Attribute63 VARCHAR2(100) NOT NULL,
       Attribute64 VARCHAR2(100) NOT NULL,
       Attribute65 VARCHAR2(100) NOT NULL,
       Attribute66 VARCHAR2(100) NOT NULL,
       Attribute67 VARCHAR2(100) NOT NULL,
       Attribute68 VARCHAR2(100) NOT NULL,
       Attribute69 VARCHAR2(100) NOT NULL,
       Attribute70 VARCHAR2(100) NOT NULL,
       Attribute71 VARCHAR2(100) NOT NULL,
       Attribute72 VARCHAR2(100) NOT NULL,
       Attribute73 VARCHAR2(100) NOT NULL,
       Attribute74 VARCHAR2(100) NOT NULL,
       Attribute75 VARCHAR2(100) NOT NULL,
       Attribute76 VARCHAR2(100) NOT NULL,
       Attribute77 VARCHAR2(100) NOT NULL,
       Attribute78 VARCHAR2(100) NOT NULL,
       Attribute79 VARCHAR2(100) NOT NULL,
       Attribute80 VARCHAR2(100) NOT NULL,
       Attribute81 VARCHAR2(100) NOT NULL,
       Attribute82 VARCHAR2(100) NOT NULL,
       Attribute83 VARCHAR2(100) NOT NULL,
       Attribute84 VARCHAR2(100) NOT NULL,
       Attribute85 VARCHAR2(100) NOT NULL,
       Attribute86 VARCHAR2(100) NOT NULL,
       Attribute87 VARCHAR2(100) NOT NULL,
       Attribute88 VARCHAR2(100) NOT NULL,
       Attribute89 VARCHAR2(100) NOT NULL,
       Attribute90 VARCHAR2(100) NOT NULL,
       Attribute91 VARCHAR2(100) NOT NULL,
       Attribute92 VARCHAR2(100) NOT NULL,
       Attribute93 VARCHAR2(100) NOT NULL,
       Attribute94 VARCHAR2(100) NOT NULL,
       Attribute95 VARCHAR2(100) NOT NULL,
       Attribute96 VARCHAR2(100) NOT NULL,
       Attribute97 VARCHAR2(100) NOT NULL,
       Attribute98 VARCHAR2(100) NOT NULL,
       Attribute99 VARCHAR2(100) NOT NULL,
       Attribute100 VARCHAR2(100) NOT NULL,
       PRIMARY KEY(ID)
);
